apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-cards-app
  labels:
    app: bank-cards
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-cards
  template:
    metadata:
      labels:
        app: bank-cards
    spec:
      containers:
        - name: app
          image: bank-cards:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/bank_cards_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: JWT_SECRET
              value: "my-super-secret-jwt-key-32-bytes-long"
            - name: ENCRYPTION_SECRET
              value: "BankCardsKey1234"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"